Core:
    #The maximum distance between two telepads, in blocks, measured in a straight line. 0 for infinite
    maxTelepadDistance: 0
    disableTeleportMessage: false

    #Commonly used center block IDs: Lapis block: 22; Gold block: 41; Diamond block: 57; Moss stone: 48
    telepadCenterID: 22

    #Put the player on the slab across from the sign instead of on the pressure plate. Useful alternative to long cooldowns on high latency servers
    useSlabAsDestination: false

    #Allow both single and double slabs to be used, else only allow double slabs
    allowSingleSlabs: false

    #Teleport pets with the player?
    teleportPets: true

    #Check for new versions on startup
    versionCheck: true
Time:
    disableTeleportWait: false
    
    #If teleport wait is not disabled, this is the number of seconds the player must hold still before they are teleported
    sendWait: 3

    #This is the number of seconds between when players may use telepads. Minimum 3 sec (less can cause issues)
    telepadCooldown: 5
Economy:
    #Disable economy even if one is detected. This allows use of all slab types.
    disableEconomy: false
    teleportCost: 0

    #Stone: 0; Sandstone: 1; Cobblestone: 3; Brick: 4; Stone Brick: 5
    #PLEASE NOTE: Wood slabs were changed in MC 1.3 and were removed in BT 1.3. Note the missing 2 above.
    telepadSurroundingNormal: 0 
    telepadSurroundingFree: 1
BlueTelepadsMessages:
#To disable a message completely, set it to "". For example: Charged: "" 
    Core:
        TeleportWaitNoName: "Preparing to send you!"
        TeleportWaitWithName: "Preparing to send you to"
        WaitInstruction: "Stand on the center of the pad."
        NoWaitNoName: "You have been teleported!"
        NoWaitWithName: "You have been teleported to"
        LocationStored: "Telepad location stored."
        ProcessReset: "Link process reset."
        Activated: "Telepad activated!"
        Teleport: "Here goes nothing!"
        Reset: "Telepad reset."
    Error:
        Distance: "Error: Telepads are too far apart!"
        AlreadyLinked: "Error: This telepad seems to be linked already!"
        AlreadyLinkedInstruction: "You can reset it by breaking the pressure pad on top of it, then tapping the lapis with redstone."
        Reflexive: "Error: You cannot connect a telepad to itself."
        PlayerMoved: "You're not on the center of the pad! Cancelling teleport."
        OutOfAbsRange: BlueTelepads cannot link telepads at locations this far from 0,0."
    Economy:
        InsufficientFunds: "You don't have enough to pay for a teleport."
        Charged: "You have been charged"
    Permission:
        Use: "You do not have permission to use telepads."
        Create: "You do not have permission to create a telepad!"
        CreateFree: "You do not have permission to create a free telepad."
configVer: 3