name: BlueTelepads
main: com.MoofIT.Minecraft.BlueTelepads.BlueTelepads
version: 1.3
description: Seamless, commandless, admin or player controlled multiworld teleport for Minecraft
author: Southpaw018
website: http://www.moofit.com
depend: [Vault]

permissions:
  bluetelepads.use:
    description: Allows the use of telepads
    default: true
  bluetelepads.create:
    description: Allows the creation of pay-to-use telepads
    default: op
  bluetelepads.createfree:
    description: Allows the creation of free telepads
    default: op
  bluetelepads.destroy:
    description: Allows destruction of signs for active (linked and not reset) pads
    default: op
  bluetelepads.alwaysfree:
    description: Grants free teleports on all pads
    default: false
