name: BlueTelepads
main: com.MoofIT.Minecraft.BlueTelepads.BlueTelepads
version: 1.0
description: Seamless, commandless, admin or player controlled multiworld teleport for Minecraft
author: Southpaw018
website: http://www.moofit.com